/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CalendarEntry } from "./utils/calendar-entry";
export namespace Components {
    interface ChartsDthree {
        "data": string;
        "height": number;
        "width": number;
    }
    interface ComboBox {
    }
    interface MyComponent {
        "dayNames": string[];
        "monthNames": string[];
        "showFillDays": boolean;
    }
    interface PrimeTable {
        "lists": string;
    }
    interface ZCombobox {
        "defaultOptions": any[];
        "isClearable": boolean;
        "isDisabled": boolean;
        "isMultiple": boolean;
        "isOrdered": boolean;
        "isRequired": boolean;
        "label": string;
        "placeholder": string;
    }
}
export interface MyComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyComponentElement;
}
export interface ZComboboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLZComboboxElement;
}
declare global {
    interface HTMLChartsDthreeElement extends Components.ChartsDthree, HTMLStencilElement {
    }
    var HTMLChartsDthreeElement: {
        prototype: HTMLChartsDthreeElement;
        new (): HTMLChartsDthreeElement;
    };
    interface HTMLComboBoxElement extends Components.ComboBox, HTMLStencilElement {
    }
    var HTMLComboBoxElement: {
        prototype: HTMLComboBoxElement;
        new (): HTMLComboBoxElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPrimeTableElement extends Components.PrimeTable, HTMLStencilElement {
    }
    var HTMLPrimeTableElement: {
        prototype: HTMLPrimeTableElement;
        new (): HTMLPrimeTableElement;
    };
    interface HTMLZComboboxElement extends Components.ZCombobox, HTMLStencilElement {
    }
    var HTMLZComboboxElement: {
        prototype: HTMLZComboboxElement;
        new (): HTMLZComboboxElement;
    };
    interface HTMLElementTagNameMap {
        "charts-dthree": HTMLChartsDthreeElement;
        "combo-box": HTMLComboBoxElement;
        "my-component": HTMLMyComponentElement;
        "prime-table": HTMLPrimeTableElement;
        "z-combobox": HTMLZComboboxElement;
    }
}
declare namespace LocalJSX {
    interface ChartsDthree {
        "data"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface ComboBox {
    }
    interface MyComponent {
        "dayNames"?: string[];
        "monthNames"?: string[];
        "onDayChanged"?: (event: MyComponentCustomEvent<CalendarEntry>) => void;
        "onMonthChanged"?: (event: MyComponentCustomEvent<CalendarEntry>) => void;
        "showFillDays"?: boolean;
    }
    interface PrimeTable {
        "lists"?: string;
    }
    interface ZCombobox {
        "defaultOptions"?: any[];
        "isClearable"?: boolean;
        "isDisabled"?: boolean;
        "isMultiple"?: boolean;
        "isOrdered"?: boolean;
        "isRequired"?: boolean;
        "label"?: string;
        "onZ-change"?: (event: ZComboboxCustomEvent<any>) => void;
        "placeholder"?: string;
    }
    interface IntrinsicElements {
        "charts-dthree": ChartsDthree;
        "combo-box": ComboBox;
        "my-component": MyComponent;
        "prime-table": PrimeTable;
        "z-combobox": ZCombobox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "charts-dthree": LocalJSX.ChartsDthree & JSXBase.HTMLAttributes<HTMLChartsDthreeElement>;
            "combo-box": LocalJSX.ComboBox & JSXBase.HTMLAttributes<HTMLComboBoxElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "prime-table": LocalJSX.PrimeTable & JSXBase.HTMLAttributes<HTMLPrimeTableElement>;
            "z-combobox": LocalJSX.ZCombobox & JSXBase.HTMLAttributes<HTMLZComboboxElement>;
        }
    }
}
